schema_version = "1.0.0"

id = "render_multiple_instances"
version = "3.2.1"
name = "Render Multiple Instances"
tagline = "Render animations and Flipbooks faster with multiple instances"
maintainer = "Daniele Stochino <dshot92@gmail.com>"

type = "add-on"

website = "https://github.com/dshot92/render-multiple-instances"

tags = ["Render", "Pipeline"]

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]

copyright = ["2020-2024 Daniele Stochino"]

[permissions]
files = "Save and read exports images"

[build]
paths_exclude_pattern = [
  "__pycache__/",
  "/.git/",
  "/*.zip",
  "/tests/",
]
