name: Old - Build Extension

on:
  push:
    branches:
      - main
      - dev
      - test
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering from the Actions tab

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Build Blender Extension
          uses: dshot92/build-blender-extension@v1.1.0
